<?php

return array (
  'version' => '5.4',
  'title' => '카테고리',
  'type' => 'wp-taxonomy_category',
  'id' => '5e715dbace32f',
  'updated' => 1609651355,
  'columns' => 
  array (
    '5ee06be19494f' => 
    array (
      'type' => 'column-termid',
      'label' => 'ID',
      'width' => '20',
      'width_unit' => 'px',
      'export' => 'off',
      'sort' => 'off',
      'filter' => 'off',
      'filter_label' => '',
    ),
    '5e715dd5ac0fa' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Notion 스타일의 아이콘',
      'width' => '100',
      'width_unit' => 'px',
      'field' => 'field_5f58611d5426f',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    'name' => 
    array (
      'type' => 'name',
      'label' => '이름',
      'width' => '160',
      'width_unit' => 'px',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
    ),
    'description' => 
    array (
      'type' => 'description',
      'label' => '설명',
      'width' => '',
      'width_unit' => '%',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
    ),
    'posts' => 
    array (
      'type' => 'posts',
      'label' => '개수',
      'width' => '',
      'width_unit' => '%',
      'export' => 'on',
      'sort' => 'on',
    ),
    '5f5865c1e278a' => 
    array (
      'type' => 'column-acf_field',
      'label' => '리스트 보이기',
      'width' => '80',
      'width_unit' => 'px',
      'field' => 'field_5f58628672d78',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    '5f5865c1e278d' => 
    array (
      'type' => 'column-acf_field',
      'label' => '메인 포스트 보이기',
      'width' => '80',
      'width_unit' => 'px',
      'field' => 'field_5f585ed2f2d3b',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);