<?php

return array (
  'version' => '5.4',
  'title' => '개발 포스트',
  'type' => 'dev',
  'id' => '60003225230f1',
  'updated' => 1612744883,
  'columns' => 
  array (
    '5ffa709b4a6ff' => 
    array (
      'type' => 'column-status',
      'label' => '👀',
      'width' => '50',
      'width_unit' => 'px',
      'use_icon' => '1',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'on',
      'filter_label' => '👀',
    ),
    'title' => 
    array (
      'type' => 'title',
      'label' => '제목',
      'width' => '',
      'width_unit' => '%',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
    ),
    '60194d92601de' => 
    array (
      'type' => 'column-taxonomy',
      'label' => '카테고리',
      'width' => '',
      'width_unit' => '%',
      'taxonomy' => 'dev_category',
      'term_link_to' => 'filter',
      'number_of_items' => '10',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'enable_term_creation' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    '6000350827c62' => 
    array (
      'type' => 'column-taxonomy',
      'label' => '태그',
      'width' => '',
      'width_unit' => '%',
      'taxonomy' => 'dev_tag',
      'term_link_to' => 'filter',
      'number_of_items' => '10',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'enable_term_creation' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    '6009a55198990' => 
    array (
      'type' => 'column-acf_field',
      'label' => '🥝',
      'width' => '50',
      'width_unit' => 'px',
      'field' => 'field_60002215d037b',
      'image_size' => 'cpac-custom',
      'image_size_w' => '24',
      'image_size_h' => '24',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    'date' => 
    array (
      'type' => 'date',
      'label' => '일자',
      'width' => '',
      'width_unit' => '%',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'off',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'off',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);