<?php

return array(
  'version' => '5.4',
  'title' => 'SEO',
  'type' => 'dev',
  'id' => '60003128cf00b',
  'updated' => 1610625320,
  'columns' =>
  array(
    '5ffa709b4a6ff' =>
    array(
      'type' => 'column-status',
      'label' => '👀',
      'width' => '50',
      'width_unit' => 'px',
      'use_icon' => '1',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'on',
      'filter_label' => '',
    ),
    'title' =>
    array(
      'type' => 'title',
      'label' => '제목',
      'width' => '',
      'width_unit' => '%',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
    ),
    'categories' =>
    array(
      'type' => 'categories',
      'label' => '카테고리',
      'width' => '15',
      'width_unit' => '%',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'enable_term_creation' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'on',
    ),
    'tags' =>
    array(
      'type' => 'tags',
      'label' => '태그',
      'width' => '15',
      'width_unit' => '%',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'enable_term_creation' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    'date' =>
    array(
      'type' => 'date',
      'label' => '일자',
      'width' => '',
      'width_unit' => '%',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'off',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
    ),
    '60002af5416cc' =>
    array(
      'type' => 'post_type',
      'label' => 'Type',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
    ),
  ),
  'settings' =>
  array(
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_filter_category' => 'off',
    'hide_filter_post_format' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);
