<?php

return array (
  'version' => '5.4',
  'title' => '모든 일',
  'type' => 'work',
  'id' => '6003c0f689545',
  'updated' => 1613713100,
  'columns' => 
  array (
    '600eee5447024' => 
    array (
      'type' => 'column-password_protected',
      'label' => '🔑',
      'width' => '30',
      'width_unit' => 'px',
      'export' => 'off',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
    ),
    '6003c10e1bb34' => 
    array (
      'type' => 'column-taxonomy',
      'label' => '클라이언트',
      'width' => '100',
      'width_unit' => 'px',
      'taxonomy' => 'work_category',
      'term_link_to' => 'filter',
      'number_of_items' => '10',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'enable_term_creation' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    'title' => 
    array (
      'type' => 'title',
      'label' => '제목',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
    ),
    '60137b3eb501c' => 
    array (
      'type' => 'column-acf_field',
      'label' => '🚀 Start Project',
      'width' => '150',
      'width_unit' => 'px',
      'field' => 'field_6013781316ed7',
      'date_format' => 'acf',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
    ),
    '60137b3eb501f' => 
    array (
      'type' => 'column-acf_field',
      'label' => '🎉 End Project',
      'width' => '140',
      'width_unit' => 'px',
      'field' => 'field_601378605e5d4',
      'date_format' => 'acf',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
    ),
    '601779680b2d6' => 
    array (
      'type' => 'column-acf_field',
      'label' => '⛰',
      'width' => '140',
      'width_unit' => 'px',
      'field' => 'field_60177abd63562',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    '60055235305c6' => 
    array (
      'type' => 'column-postid',
      'label' => 'ID',
      'width' => '80',
      'width_unit' => 'px',
      'before' => '',
      'after' => '',
      'export' => 'off',
      'sort' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    'date' => 
    array (
      'type' => 'date',
      'label' => '날짜',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'off',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);