<?php

return array (
  'version' => '5.4',
  'title' => '일정',
  'type' => 'work',
  'id' => '601379afc6e3b',
  'updated' => 1611889356,
  'columns' => 
  array (
    '6003c10e1bb34' => 
    array (
      'type' => 'column-taxonomy',
      'label' => '클라이언트',
      'width' => '100',
      'width_unit' => 'px',
      'taxonomy' => 'work_category',
      'term_link_to' => 'filter',
      'number_of_items' => '10',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'enable_term_creation' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    '601378f097095' => 
    array (
      'type' => 'column-acf_field',
      'label' => '🚀 Start Project',
      'width' => '140',
      'width_unit' => 'px',
      'field' => 'field_6013781316ed7',
      'date_format' => 'acf',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'on',
      'filter_label' => '',
      'filter_format' => '',
    ),
    '601378f097098' => 
    array (
      'type' => 'column-acf_field',
      'label' => '🎉 End Project',
      'width' => '140',
      'width_unit' => 'px',
      'field' => 'field_601378605e5d4',
      'date_format' => 'acf',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
    ),
    'title' => 
    array (
      'type' => 'title',
      'label' => '제목',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'off',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);